@startuml
package src{

    ' =======================
    ' External Types
    ' =======================
    class ClassReader
    class ClassVisitor
    class Path
    class PrintStream
    class FileUtils

    ' =======================
    ' Reporter API
    ' =======================
    interface Reporter {
        +void startFile(classFile: Path)
        +void report(checkName: String, className: String, message: String)
        +void endFile(classFile: Path)
    }

    class ConsoleReporter {
        - {final} out: PrintStream
        +ConsoleReporter(out: PrintStream )
        +startFile(classFile: Path): void
        +report(checkName: String, className: String, message: String): void
        +endFile(classFile: Path): void
    }

    ' =======================
    ' LintCheck API
    ' =======================
    interface LintCheck {
        +name(): String
        +runOnClass(reader: ClassReader, reporter:Reporter): void
    }

    ' =======================
    ' Concrete Checks
    ' =======================
    together{
        class NamingConventionCheck{
            -reporter: Reporter
            -simpleClassName: String

            ~NamingConventionCheck()
            +name(): String
            +runOnClass(reader: ClassReader, reporter: Reporter): void
            -report(message: String): void
            +visit(version: int, access: int, name: String, signature: String, superName: String, interfaces: String[]): void
            +visitMethod(access: int, name: String, descriptor: String, signature: String, exceptions: String[]): MethodVisitor
            +visitField(access: int, name: String, descriptor: String, signature: String, value: Object): FieldVisitor
        }
        class NonPublicConstructorCheck{
            -reporter: Reporter
            -isPublicClass: boolean
            -simpleClassName: String
            -isAbstractOrInterface: boolean
            -hasAnyCtor: boolean
            -hasPublicOrProtectedCtor: boolean

            ~NonPublicConstructorCheck()
            +name(): String
            +runOnClass(reader: ClassReader, reporter: Reporter): void
            -report(message: String): void
            +visit(version: int, access: int, name: String, signature: String, superName: String, interfaces: String[]): void
            +visitMethod(access: int, name: String, descriptor: String, signature: String, exceptions: String[]): MethodVisitor
            +visitEnd(): void
        }
        class LongMethodCheck {
            -reporter: Reporter
            -simpleClassName: String
            -{final} maxInstructions: int

            ~LongMethodCheck(maxInstructions: int)
            +runOnClass(reader: ClassReader, reporter: Reporter): void
            -report(methodName:String, count: int): void
            +visit(version: int, access: int, name: String, signature: String, superName: String, interfaces: String[]): void
            +visitMethod(access: int, name: String, descriptor: String, signature: String, exceptions: String[]): MethodVisitor
        }
        class MagicNumberCheck{
            -reporter: Reporter
            -simpleClassName: String

            ~MagicNumberCheck()
            +name(): String
            +runOnClass(reader: ClassReader, reporter:Reporter): void
            -report(methodName: String, value: Number): void
            -isWhiteListedNumber(n: Number): boolean
            +visit(version: int, access: int, name: String, signature: String, superName: String, interfaces: String[]): void
            +visitMethod(access: int, name: String, descriptor: String, signature: String, exceptions: String[]): MethodVisitor

        }
        class UnusedFieldCheck {
            -reporter: Reporter
            -simpleClassName: String
            -classInternalName: String
            -{final} privateFields: Set<String>
            -{final} usedFields: Set<String>

            ~UnusedFieldCheck()
            +name(): String
            +runOnClass(reader: ClassReader, reporter: Reporter): void
            -report(message: String): void
            +visit(version: int, access: int, name: String, signature: String, superName: String, interfaces: String[]): void
            +visitField(access: int, name: String, descriptor: String, signature: String, value: Object): FieldVisitor
            +visitMethod(access: int, name: String, descriptor: String, signature: String, exceptions: String[]): MethodVisitor
            +visitEnd(): void

        }
        class NullReturnCheck{
            -reporter: Reporter
            -simpleClassName: String

            ~NullReturnCheck()
            +name(): String
            +runOnClass(reader: ClassReader, reporter: Reporter): void
            -report(methodName: String): void
            +visit(version: int, access: int, name: String, signature: String, superName: String, interfaces: String[]): void
            +visitMethod(access: int, name: String, descriptor: String, signature: String, exceptions: String[]): MethodVisitor
        }
    }

    Reporter <|.. ConsoleReporter
    LintCheck <|.. NamingConventionCheck
    LintCheck <|.. NonPublicConstructorCheck
    LintCheck <|.. LongMethodCheck
    LintCheck <|.. MagicNumberCheck
    LintCheck <|.. UnusedFieldCheck
    LintCheck <|.. NullReturnCheck

    ClassVisitor <|.. NamingConventionCheck
    ClassVisitor <|.. NonPublicConstructorCheck
    ClassVisitor <|.. LongMethodCheck
    ClassVisitor <|.. MagicNumberCheck
    ClassVisitor <|.. UnusedFieldCheck
    ClassVisitor <|.. NullReturnCheck

    NamingConventionCheck ..> MethodVisitor
    MagicNumberCheck ..> MethodVisitor
    LongMethodCheck ..> MethodVisitor
    UnusedFieldCheck ..> MethodVisitor
    NonPublicConstructorCheck ..> MethodVisitor
    NullReturnCheck ..> MethodVisitor
    UnusedFieldCheck ..> FieldVisitor
    NamingConventionCheck ..> FieldVisitor

    NamingConventionCheck ..> ClassReader
    MagicNumberCheck ..> ClassReader
    LongMethodCheck ..> ClassReader
    UnusedFieldCheck ..> ClassReader
    NonPublicConstructorCheck ..> ClassReader
    NullReturnCheck ..> ClassReader

    NamingConventionCheck --> Reporter
    MagicNumberCheck --> Reporter
    LongMethodCheck --> Reporter
    UnusedFieldCheck --> Reporter
    NonPublicConstructorCheck --> Reporter
    NullReturnCheck --> Reporter






    ' =======================
    ' Linter Runner
    ' =======================
    class LinterRunner {
        - {final} checks: List<LintCheck>
        - {final} reporter: Reporter
        +LinterRunner(checks: List<LintCheck>, reporter: Reporter)
        +runOnPath(root: Path): void
    }

    Main --> LinterRunner
    Main --> Reporter
    Main --> LintCheck
    Main --> Path

    LinterRunner --> Reporter
    LinterRunner --> LintCheck
    LinterRunner ..> ClassReader
    LinterRunner --> Path
    LinterRunner ..> FileUtils

    ConsoleReporter --> PrintStream

    ' =======================
    ' Main
    ' =======================
    class Main {
        + {static} void main(String[] args)
    }
}
@enduml
